<a href="https://colab.research.google.com/github/Demonytro/DS_Hw1/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Reinstall numpy using pip with the latest version
!pip install numpy --upgrade
# Import numpy as np
import numpy as np
np.__version__

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.6/17.6 MB 64.1 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.22.4
    Uninstalling numpy-1.22.4:
      Successfully uninstalled numpy-1.22.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.25.1 which is incompatible.
tensorflow 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.25.1 which is incompatible.


'1.22.4'

In [2]:
import numpy as np
np.__version__

'1.25.1'

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.


In [16]:
# create a np.array vector with 10 elements from 1 to 10 with dtype=float
a = np.array(object=[1,2,3,4,5,6,7,8,9,10], dtype=int)

# print the vector
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [5]:
# Create a numpy matrix with a specific data type = int
A = np.array([[0, 0, 0],[0, 0, 0]], dtype=int)

# Display the result
print(A)

# створіть вектор з нулями
b = np.zeros((3,3))

# відобразіть результат
print(b)

[[0 0 0]
 [0 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3.     Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.


In [13]:
# створіть матрицю з рандомними значеннями
c = np.random.randint(1, 10, (5, 5))


# відобразіть результат
print(c)

[[9 2 3 1 1]
 [9 8 7 6 2]
 [1 1 8 5 5]
 [9 1 5 5 6]
 [8 7 7 2 7]]


4.     Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [18]:
# створіть матрицю з рандомними значеннями
b = np.random.random((4,4))
c = np.random.rand(4, 4)


# відобразіть результат
print(b)
print(c)

[[0.04134905 0.66932475 0.86632338 0.139101  ]
 [0.09770663 0.83920542 0.08826744 0.96869353]
 [0.48125063 0.62258334 0.45672868 0.78482207]
 [0.40582784 0.59968507 0.16281182 0.95664215]]
[[0.97377361 0.23916816 0.53056933 0.69570108]
 [0.13878223 0.61133551 0.36776085 0.1276472 ]
 [0.2601824  0.19104549 0.74528813 0.51392671]
 [0.98939954 0.37541491 0.00554897 0.2151131 ]]


5.     Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.


In [6]:
a = np.random.randint(1, 10, (5))
b = np.random.randint(1, 10, (5))

print(a)
print(b)

# відобразіть додавання
c = a + b
print(c)

# відобразіть віднімання
c = a - b
print(c)

# відобразіть множення
c = a * b
print(c)

[8 9 7 8 8]
[5 2 9 3 8]
[13 11 16 11 16]
[ 3  7 -2  5  0]
[40 18 63 24 64]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.


In [5]:
b = np.random.random(7)
c = np.random.rand(7)


# відобразіть результат
print(b)
print(c)

d = b@c
# відобразіть результат
print(d)

[0.49270391 0.59976861 0.94075773 0.61160118 0.62897614 0.9326583
 0.66168589]
[0.70469018 0.59634595 0.42618811 0.40072278 0.30560744 0.26604265
 0.11803386]
1.8693434808979268


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [13]:
a = np.random.randint(1, 10, (2,2))
b = np.random.randint(1, 10, (2,3))

print(a)
print(b)

# відобразіть множення
# c = a * b
# print(c)

print(np.dot(a, b))
# print(np.dot(b, a))

[[7 4]
 [1 8]]
[[4 9 9]
 [6 3 5]]
[[52 75 83]
 [52 33 49]]



8.    Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.


In [17]:
a = np.random.randint(1, 10, (3,3))
print(a)
a_inv = np.linalg.inv(a)
print(a_inv)

[[4 1 2]
 [2 1 5]
 [8 7 4]]
[[ 0.3875 -0.125  -0.0375]
 [-0.4    -0.      0.2   ]
 [-0.075   0.25   -0.025 ]]



9.    Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.


In [26]:
b = np.random.random((4,4))
print(b)
b_transp = b.T
print(b_transp)
C = np.transpose(b)
print(C)

[[0.53873467 0.79964063 0.73163658 0.33811702]
 [0.35169365 0.71735455 0.80937667 0.18182422]
 [0.19121657 0.87332686 0.95749618 0.23102528]
 [0.06875394 0.09212887 0.10770459 0.4167709 ]]
[[0.53873467 0.35169365 0.19121657 0.06875394]
 [0.79964063 0.71735455 0.87332686 0.09212887]
 [0.73163658 0.80937667 0.95749618 0.10770459]
 [0.33811702 0.18182422 0.23102528 0.4167709 ]]
[[0.53873467 0.35169365 0.19121657 0.06875394]
 [0.79964063 0.71735455 0.87332686 0.09212887]
 [0.73163658 0.80937667 0.95749618 0.10770459]
 [0.33811702 0.18182422 0.23102528 0.4167709 ]]



10.    Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.


In [20]:
a = np.random.randint(1, 10, (3,4))
b = np.random.randint(1, 10, (4))
c = a * b
print(a)
print(b)
print(c)

[[8 1 6 4]
 [6 1 3 3]
 [4 5 7 6]]
[7 2 3 8]
[[56  2 18 32]
 [42  2  9 24]
 [28 10 21 48]]



11.    Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [37]:
a = np.random.random((3,4))
b = np.random.random((4))
c = a * b
print(a)
print(b)
print(c)

[[0.90913161 0.58029042 0.49196103 0.28700612]
 [0.33038231 0.37833228 0.50833381 0.43691741]
 [0.76780674 0.94540561 0.80585048 0.67765027]]
[0.50799761 0.18113017 0.02848569 0.11551632]
[[0.46183669 0.1051081  0.01401385 0.03315389]
 [0.16783342 0.06852739 0.01448024 0.05047109]
 [0.39004399 0.17124148 0.02295521 0.07827967]]


12.    Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.



In [23]:
a = np.random.randint(1, 10, (2,2))
b = np.random.randint(1, 10, (2,2))
c = a * b
print(a)
print(b)
print(c)

[[3 6]
 [8 9]]
[[1 3]
 [8 8]]
[[ 3 18]
 [64 72]]



13.    Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.


In [32]:
a = np.random.randint(1, 10, (2,2))
b = np.random.randint(1, 10, (2,2))
c = np.multiply(a, b)
print(a)
print(b)
print(c)

C = np.dot(a, b)

# print the matrix C
print(C)

# use a magic function
D = a@b

# print the matrix D
print(D)

[[3 4]
 [4 9]]
[[2 9]
 [5 7]]
[[ 6 36]
 [20 63]]
[[26 55]
 [53 99]]
[[26 55]
 [53 99]]



14.    Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.


In [31]:
a = np.random.randint(1, 100, (5,5))
b = a.cumsum()
print(a)
print(b)
print(b[::-1])
print(b[:-1])
print(b[-1])

[[69 14 25 98 72]
 [29 10  3 95 98]
 [25  8 85 61 35]
 [48 58 21 46 93]
 [94 61 82 35 17]]
[  69   83  108  206  278  307  317  320  415  513  538  546  631  692
  727  775  833  854  900  993 1087 1148 1230 1265 1282]
[1282 1265 1230 1148 1087  993  900  854  833  775  727  692  631  546
  538  513  415  320  317  307  278  206  108   83   69]
[  69   83  108  206  278  307  317  320  415  513  538  546  631  692
  727  775  833  854  900  993 1087 1148 1230 1265]
1282



15.    Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [36]:
a = np.random.randint(1, 10, (2,2))
b = np.random.randint(1, 10, (2,2))
c = a - b
print(a)
print(b)
print(f"знайдіть їхню різницю {c}")

[[8 1]
 [5 4]]
[[2 6]
 [8 4]]
знайдіть їхню різницю [[ 6 -5]
 [-3  0]]


16.     Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.


In [50]:
a = np.random.random((3,3))

# c = a * b
print(a)

# print(c)

[[0.61844214 0.9949937  0.39344401]
 [0.84941716 0.53764372 0.04103732]
 [0.03627932 0.05456304 0.234381  ]]



17.    Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.


In [45]:
a = np.random.randint(1, 10, (3,4))
print(a)
print(a ** 2)
print(np.power(a, 2))

print(np.square(a))

[[6 6 5 3]
 [7 3 7 5]
 [7 6 8 8]]
[[36 36 25  9]
 [49  9 49 25]
 [49 36 64 64]]
[[36 36 25  9]
 [49  9 49 25]
 [49 36 64 64]]
[[36 36 25  9]
 [49  9 49 25]
 [49 36 64 64]]



18.    Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [47]:
a = np.random.randint(1, 50, (4))
print(a)
print(np.sqrt(a))

[ 4 35 38 32]
[2.         5.91607978 6.164414   5.65685425]


Домашнє завдання

#---

    Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

    Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

    Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

Домашня робота здається у вигляді Jupyter файлу Hw1.ipynb.

    Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

    Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

    Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

    Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

    Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

    Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

    Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

    Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

    Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

    Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

    Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

    Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

    Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

    Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

    Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
